# config/routes/routes.yaml

app_main_route:
    path: /
    controller: App\Controller\HomeController:home

# User management routes
app_security:
    resource: 'security/routes.yaml'
    prefix: /security

app_handle_home_form:
    path: /form/home
    controller: App\Controller\HomeController:handleHomeForm
    condition: "request.isXmlHttpRequest()"

app_condition_use:
    path: /app/cou/
    controller: App\Controller\HomeController:conditionsOfUse

app_link_manager:
    path: /link/manager/
    controller: App\Controller\LinkController:linkManager
    condition: "request.isXmlHttpRequest()"

app_link_manager_controller:
    path: /link/manager/controller
    controller: App\Controller\LinkController:linkManagerController
    condition: "request.isXmlHttpRequest()"

app_link_manager_check_uuid:
    path: /link/manager/checkuuid/
    controller: App\Controller\LinkController:checkUniqueUuid
    condition: "request.isXmlHttpRequest()"

app_link_review_link:
    path: /check
    controller: App\Controller\LinkController:reviewLink
    condition: "request.isXmlHttpRequest()"

app_link_match:
    path: /{uuid}/
    controller: App\Controller\LinkController:linkHandler