monolog:
    channels: ['linksecurity', 'linkVisitDb', 'geo2ip']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        linksecurity:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/linksecurity.log'
            channels: [linksecurity]
            max_files: 5
        geo2ip:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/geo2ip.log'
            channels: [geo2ip]
            max_files: 5
        linkVisitDb:
            type:   service
            id: App\Util\MonologHandler\MonologLinkVisitHandler
            channels: [linkVisitDb]