monolog:
    channels: ['linksecurity', 'linkVisitDb', 'geo2ip']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        linksecurity:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/linksecurity.log'
            channels: [linksecurity]
            max_files: 5
        geo2ip:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/geo2ip.log'
            channels: [geo2ip]
            max_files: 5
        linkVisitDb:
            type:   service
            id: App\Util\MonologHandler\MonologLinkVisitHandler
            channels: [linkVisitDb]
